apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iptvrecordings.herlon214.github.io
spec:
  group: herlon214.github.io
  scope: Namespaced
  names:
    plural: iptvrecordings
    singular: iptvrecording
    kind: IptvRecording
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
                fileName:
                  type: string
                schedule:
                  type: string
                duration:
                  type: string
                folder:
                  type: string
                hostPath:
                  type: string

      subresources:
        status: {}
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: iptv-recording-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: herlon214.github.io/v1
    resource: iptvrecordings
  childResources:
    - apiVersion: v1
      resource: pods
  hooks:
    sync:
      webhook:
        url: http://iptv-recording-controller.metacontroller/sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iptv-recording-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iptv-recording-controller
  template:
    metadata:
      labels:
        app: iptv-recording-controller
    spec:
      containers:
        - name: controller
          image: ghcr.io/herlon214/iptv-recording:v0.3.8
          args: ["k8s"]
---
apiVersion: v1
kind: Service
metadata:
  name: iptv-recording-controller
  namespace: metacontroller
spec:
  selector:
    app: iptv-recording-controller
  ports:
    - port: 80
      targetPort: 8080